// Auto-generated by scripts/gen_homepage_images.py
// Run: python scripts/gen_homepage_images.py
// then commit + push the updated URLs below

const homepageImages = {
  hero: '',
  std: '',
  glp1: '',
  ckd: '',
  foreign: '',
}

export default homepageImages
