"""
gen_homepage_images.py — สร้างรูปหน้าแรกด้วย FLUX.1 แล้ว upload Supabase Storage
และเขียน URL ลง src/config/homepage-images.ts อัตโนมัติ

Run:
  ANTHROPIC_API_KEY=... TOGETHER_API_KEY=... NEXT_PUBLIC_SUPABASE_URL=... SUPABASE_SECRET=...
  python scripts/gen_homepage_images.py
"""

import os
import re
import sys
import uuid
import requests
from pathlib import Path
from supabase import create_client

TOGETHER_KEY = os.environ["TOGETHER_API_KEY"]
SUPABASE_URL = os.environ["NEXT_PUBLIC_SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SECRET"]

CONFIG_PATH = Path(__file__).parent.parent / "src" / "config" / "homepage-images.ts"

# Shared framing hints so FLUX doesn't crop heads / tops of faces
FRAMING = (
    "full body or medium shot, heads fully visible with space above, "
    "well-framed centered composition, no cropped faces, eye-level camera"
)

IMAGES = {
    "hero": (
        f"modern private Thai medical clinic interior, warm natural lighting, "
        f"friendly Thai female doctor in white coat smiling at patient, "
        f"clean minimal design, soft green and cream tones, professional, "
        f"{FRAMING}, no text, 16:9"
    ),
    "std": (
        f"young Thai woman in private medical consultation, safe comfortable clinic room, "
        f"soft pink and white tones, doctor listening attentively, non-judgmental atmosphere, "
        f"professional healthcare, {FRAMING}, no text, 16:9"
    ),
    "glp1": (
        f"healthy Thai woman mid-30s smiling, vibrant fresh vegetables and healthy food, "
        f"fitness lifestyle, soft emerald green tones, weight management success, "
        f"professional medical photo, {FRAMING}, no text, 16:9"
    ),
    "ckd": (
        f"Thai elderly patient consulting with nephrologist doctor, hospital kidney clinic, "
        f"calm blue and white medical environment, caring professional atmosphere, "
        f"trust and expertise, {FRAMING}, no text, 16:9"
    ),
    "foreign": (
        f"diverse Myanmar and Cambodian workers in clean medical clinic, "
        f"health certificate checkup, professional clinic Samut Sakhon Thailand, "
        f"warm amber tones, organized efficient service, {FRAMING}, no text, 16:9"
    ),
}


def generate_image(key: str, prompt: str) -> bytes | None:
    print(f"  🎨 Generating [{key}]...")
    try:
        resp = requests.post(
            "https://api.together.xyz/v1/images/generations",
            headers={
                "Authorization": f"Bearer {TOGETHER_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": "black-forest-labs/FLUX.1-schnell",
                "prompt": prompt,
                "width": 1200,
                "height": 672,
                "steps": 4,
                "n": 1,
                "response_format": "url",
            },
            timeout=90,
        )
        resp.raise_for_status()
        url = resp.json()["data"][0]["url"]
        img = requests.get(url, timeout=30)
        img.raise_for_status()
        return img.content
    except Exception as e:
        print(f"  ❌ Generate failed for {key}: {e}")
        return None


def upload_to_storage(key: str, data: bytes) -> str | None:
    sb = create_client(SUPABASE_URL, SUPABASE_KEY)
    file_path = f"homepage/{key}-{uuid.uuid4().hex[:8]}.jpg"
    try:
        sb.storage.from_("images").upload(
            file_path,
            data,
            {"content-type": "image/jpeg", "upsert": "true"},
        )
        url = sb.storage.from_("images").get_public_url(file_path)
        print(f"  ☁️  Uploaded: {url}")
        return url
    except Exception as e:
        print(f"  ❌ Upload failed for {key}: {e}")
        return None


def write_config(urls: dict[str, str]):
    entries = "\n".join(f"  {k}: '{v}'," for k, v in urls.items())
    content = f"""// Auto-generated by scripts/gen_homepage_images.py
// Run: python scripts/gen_homepage_images.py
// then commit + push the updated URLs below

const homepageImages = {{
{entries}
}}

export default homepageImages
"""
    CONFIG_PATH.write_text(content, encoding="utf-8")
    print(f"\n✅ Config เขียนแล้ว: {CONFIG_PATH}")


def load_existing_urls() -> dict[str, str]:
    """Read current URLs from homepage-images.ts so we can keep the ones we're not regenerating."""
    if not CONFIG_PATH.exists():
        return {}
    text = CONFIG_PATH.read_text(encoding="utf-8")
    urls: dict[str, str] = {}
    for key in IMAGES:
        match = re.search(rf"{key}:\s*'([^']*)'", text)
        if match:
            urls[key] = match.group(1)
    return urls


def main():
    print("🌿 รู้ก่อนดี — Gen Homepage Images")

    # ENV ONLY: comma-separated keys to regenerate (e.g. "foreign" or "foreign,hero")
    only_env = os.environ.get("GEN_ONLY", "").strip()
    if only_env:
        targets = [k.strip() for k in only_env.split(",") if k.strip() in IMAGES]
        if not targets:
            print(f"❌ GEN_ONLY='{only_env}' ไม่มี key ที่ถูกต้อง (เลือกจาก: {', '.join(IMAGES)})")
            sys.exit(1)
        print(f"🎯 Regenerate เฉพาะ: {', '.join(targets)}")
    else:
        targets = list(IMAGES.keys())
        print("🎯 Regenerate ทั้งหมด")

    urls = load_existing_urls()

    for key in targets:
        data = generate_image(key, IMAGES[key])
        if data:
            url = upload_to_storage(key, data)
            if url:
                urls[key] = url
            else:
                urls[key] = urls.get(key, "")
        else:
            urls[key] = urls.get(key, "")

    # Fill any missing keys with empty string
    for key in IMAGES:
        urls.setdefault(key, "")

    write_config(urls)

    generated_ok = [k for k in targets if urls.get(k)]
    print(f"\n🎉 สร้างใหม่สำเร็จ {len(generated_ok)} / {len(targets)} รูป ({', '.join(generated_ok) or 'none'})")
    if len(generated_ok) < len(targets):
        failed = [k for k in targets if k not in generated_ok]
        print(f"⚠️  ล้มเหลว: {', '.join(failed)}")
        sys.exit(1)
    print("▶️  ขั้นตอนต่อไป: git add src/config/homepage-images.ts && git commit && git push")


if __name__ == "__main__":
    main()
