"""
gen_homepage_images.py — สร้างรูปหน้าแรกด้วย FLUX.1 แล้ว upload Supabase Storage
และเขียน URL ลง src/config/homepage-images.ts อัตโนมัติ

Run:
  ANTHROPIC_API_KEY=... TOGETHER_API_KEY=... NEXT_PUBLIC_SUPABASE_URL=... SUPABASE_SECRET=...
  python scripts/gen_homepage_images.py
"""

import os
import re
import sys
import uuid
import requests
from pathlib import Path
from supabase import create_client

TOGETHER_KEY = os.environ["TOGETHER_API_KEY"]
SUPABASE_URL = os.environ["NEXT_PUBLIC_SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SECRET"]

CONFIG_PATH = Path(__file__).parent.parent / "src" / "config" / "homepage-images.ts"

IMAGES = {
    "hero": (
        "modern private Thai medical clinic interior, warm natural lighting, "
        "friendly Thai female doctor in white coat smiling at patient, "
        "clean minimal design, soft green and cream tones, professional, "
        "no text, 16:9"
    ),
    "std": (
        "young Thai woman in private medical consultation, safe comfortable clinic room, "
        "soft pink and white tones, doctor listening attentively, non-judgmental atmosphere, "
        "professional healthcare, no text, 16:9"
    ),
    "glp1": (
        "healthy Thai woman mid-30s smiling, vibrant fresh vegetables and healthy food, "
        "fitness lifestyle, soft emerald green tones, weight management success, "
        "professional medical photo, no text, 16:9"
    ),
    "ckd": (
        "Thai elderly patient consulting with nephrologist doctor, hospital kidney clinic, "
        "calm blue and white medical environment, caring professional atmosphere, "
        "trust and expertise, no text, 16:9"
    ),
    "foreign": (
        "diverse Myanmar and Cambodian workers in clean medical clinic, "
        "health certificate checkup, professional clinic Samut Sakhon Thailand, "
        "warm amber tones, organized efficient service, no text, 16:9"
    ),
}


def generate_image(key: str, prompt: str) -> bytes | None:
    print(f"  🎨 Generating [{key}]...")
    try:
        resp = requests.post(
            "https://api.together.xyz/v1/images/generations",
            headers={
                "Authorization": f"Bearer {TOGETHER_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": "black-forest-labs/FLUX.1-schnell",
                "prompt": prompt,
                "width": 1200,
                "height": 672,
                "steps": 4,
                "n": 1,
                "response_format": "url",
            },
            timeout=90,
        )
        resp.raise_for_status()
        url = resp.json()["data"][0]["url"]
        img = requests.get(url, timeout=30)
        img.raise_for_status()
        return img.content
    except Exception as e:
        print(f"  ❌ Generate failed for {key}: {e}")
        return None


def upload_to_storage(key: str, data: bytes) -> str | None:
    sb = create_client(SUPABASE_URL, SUPABASE_KEY)
    file_path = f"homepage/{key}-{uuid.uuid4().hex[:8]}.jpg"
    try:
        sb.storage.from_("images").upload(
            file_path,
            data,
            {"content-type": "image/jpeg", "upsert": "true"},
        )
        url = sb.storage.from_("images").get_public_url(file_path)
        print(f"  ☁️  Uploaded: {url}")
        return url
    except Exception as e:
        print(f"  ❌ Upload failed for {key}: {e}")
        return None


def write_config(urls: dict[str, str]):
    entries = "\n".join(f"  {k}: '{v}'," for k, v in urls.items())
    content = f"""// Auto-generated by scripts/gen_homepage_images.py
// Run: python scripts/gen_homepage_images.py
// then commit + push the updated URLs below

const homepageImages = {{
{entries}
}}

export default homepageImages
"""
    CONFIG_PATH.write_text(content, encoding="utf-8")
    print(f"\n✅ Config เขียนแล้ว: {CONFIG_PATH}")


def main():
    print("🌿 รู้ก่อนดี — Gen Homepage Images")
    urls: dict[str, str] = {}

    for key, prompt in IMAGES.items():
        data = generate_image(key, prompt)
        if data:
            url = upload_to_storage(key, data)
            if url:
                urls[key] = url

    if not urls:
        print("❌ ไม่มีรูปที่สร้างสำเร็จ")
        sys.exit(1)

    # Fill missing keys with empty string
    for key in IMAGES:
        urls.setdefault(key, "")

    write_config(urls)
    success = len([u for u in urls.values() if u])
    print(f"\n🎉 เสร็จสิ้น สร้างได้ {success} / {len(IMAGES)} รูป")
    if success < len(IMAGES):
        print("⚠️  มีบางรูปสร้างไม่สำเร็จ — ดู log ด้านบน")
        sys.exit(1)
    print("▶️  ขั้นตอนต่อไป: git add src/config/homepage-images.ts && git commit && git push")


if __name__ == "__main__":
    main()
